spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001  #注册中心占用7001端口，冒号后面必须要有空格
spring:
  profiles: dev
  application:
    name: micro-service-cloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #当前的eureka-server自己不会注册进服务列表中
    server-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001  #注册中心占用7001端口，冒号后面必须要有空格
spring:
  profiles: test
  application:
    name: micro-service-cloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #当前的eureka-server自己不会注册进服务列表中
    server-url:
      defaultZone: http://eureka7001.com:7001/eureka/